# 00. data overview

## Goal
Understand the datasets, keys, sizes, time coverage, and basic entities

## Why this matters
This step is important because before comparing business and consumer behavior, we need to understand what data we have, how the tables are linked, and what the main unit of analysis should be.

In [42]:
import pandas as pd
from mdq.data import load_data

In [43]:
business, consumer, merchant, mcc = load_data()

In [44]:
print('business:')
print(business.shape)

print()
print('consumer')
print(consumer.shape)

print()
print('merchant')
print(merchant.shape)

business:
(2997593, 12)

consumer
(9832487, 12)

merchant
(2165, 5)

In [45]:
print('business num of unique:')
print(business["card_number"].nunique())

print()
print('consumer num of unique:')
print(consumer["card_number"].nunique())

print()
print('merchant num of unique:')
print(merchant["merchant_id"].nunique())

business num of unique:
25000

consumer num of unique:
80000

merchant num of unique:
2165

In [46]:
for name, df in [("business", business), ("consumer", consumer)]:
    ts = pd.to_datetime(df["transaction_timestamp"])
    print(name)
    print("min:", ts.min())
    print("max:", ts.max())
    print("days:", (ts.max() - ts.min()).days)

business
min: 2025-10-01 00:00:00
max: 2026-03-31 23:59:53
days: 181
consumer
min: 2025-10-01 00:00:00
max: 2026-03-31 23:59:49
days: 181

In [47]:
overview = pd.DataFrame({
    "business": [
        len(business),
        business["card_number"].nunique(),
        business["merchant_id"].nunique(),
    ],
    "consumer": [
        len(consumer),
        consumer["card_number"].nunique(),
        consumer["merchant_id"].nunique(),
    ]
}, index=["transactions", "unique_cards", "unique_merchants"])

overview

                  business  consumer
transactions       2997593   9832487
unique_cards         25000     80000
unique_merchants       481      2060

In [48]:
consumer.head()

,transaction_date,transaction_timestamp,transaction_amount_kzt,mcc,merchant_id,channel,bank_name,country,card_number,card_tier,tokenized,is_recurring
0,1759276800000000000,2025-10-01 00:04:00,4788,4814,MER_000064,online,Alatau City Bank,Kazakhstan,5263907968824596,Standard,False,True
1,1759276800000000000,2025-10-01 00:10:00,5240,4814,MER_000063,online,Bank RBK,Kazakhstan,5119023663984986,Standard,False,True
2,1759276800000000000,2025-10-01 00:12:00,4576,4814,MER_000066,online,Kaspi,Kazakhstan,5228590878155154,Standard,False,True
3,1759276800000000000,2025-10-01 00:37:00,6078,4814,MER_000063,online,Home Credit Bank,Kazakhstan,5338472125333693,Standard,False,True
4,1759276800000000000,2025-10-01 00:37:00,6042,4814,MER_000065,online,Kaspi,Kazakhstan,5531514712394557,Affluent,False,True

In [49]:
business.head()

,transaction_date,transaction_timestamp,transaction_amount_kzt,mcc,merchant_id,channel,bank_name,country,card_number,card_tier,tokenized,is_recurring
0,1759276800000000000,2025-10-01 00:00:00,180976,7372,MER_000007,online,Kaspi,US,5228592291438845,Business,False,True
1,1759276800000000000,2025-10-01 00:00:00,153206,7372,MER_000006,online,Home Credit Bank,US,5201495142193372,Business,False,True
2,1759276800000000000,2025-10-01 00:00:00,197106,7372,MER_000007,online,Home Credit Bank,US,5201492177677288,Business,False,True
3,1759276800000000000,2025-10-01 00:01:00,189598,7372,MER_000008,online,Kaspi,US,5176513443697635,Business,False,True
4,1759276800000000000,2025-10-01 00:03:00,700571,7311,MER_000003,online,Halyk,Russia,5100611967455520,Business,False,True

In [50]:
merchant.head()

  merchant_id  merchant_name   mcc merchant_country  recurring_capable
0  MER_000000     Google Ads  7311          Ireland               True
1  MER_000001       Meta Ads  7311          Ireland               True
2  MER_000002     TikTok Ads  7311        Singapore               True
3  MER_000003  Yandex Direct  7311           Russia               True
4  MER_000004   LinkedIn Ads  7311          Ireland               True

In [51]:
consumer.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9832487 entries, 0 to 9832486
Data columns (total 12 columns):
 #   Column                  Dtype
---  ------                  -----
 0   transaction_date        object
 1   transaction_timestamp   datetime64[ms]
 2   transaction_amount_kzt  int64
 3   mcc                     object
 4   merchant_id             object
 5   channel                 object
 6   bank_name               object
 7   country                 object
 8   card_number             object
 9   card_tier               object
 10  tokenized               bool
 11  is_recurring            bool
dtypes: bool(2), datetime64[ms](1), int64(1), object(8)
memory usage: 768.9+ MB

In [52]:
business.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2997593 entries, 0 to 2997592
Data columns (total 12 columns):
 #   Column                  Dtype
---  ------                  -----
 0   transaction_date        object
 1   transaction_timestamp   datetime64[s]
 2   transaction_amount_kzt  int64
 3   mcc                     object
 4   merchant_id             object
 5   channel                 object
 6   bank_name               object
 7   country                 object
 8   card_number             object
 9   card_tier               object
 10  tokenized               bool
 11  is_recurring            bool
dtypes: bool(2), datetime64[s](1), int64(1), object(8)
memory usage: 234.4+ MB

In [53]:
merchant.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2165 entries, 0 to 2164
Data columns (total 5 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   merchant_id        2165 non-null   object
 1   merchant_name      2165 non-null   object
 2   mcc                2165 non-null   object
 3   merchant_country   2165 non-null   object
 4   recurring_capable  2165 non-null   bool
dtypes: bool(1), object(4)
memory usage: 69.9+ KB

The competition data includes MCC codes but not full MCC names.
For interpretability, we created an auxiliary MCC reference table from Mastercard's public Quick Reference Booklet.
This table is used only for EDA interpretation and feature group naming, not as a label source.

In [54]:
mcc.head()

    mcc                                           mcc_name  page
0   742                                Veterinary Services     2
1   763                          Agricultural Cooperatives     2
2   780             Horticultural and Landscaping Services     2
3  1520    General Contractors, residential and commercial     2
4  1711  Air Conditioning, Heating, and Plumbing Contra...     2

In [56]:
mcc.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 298 entries, 0 to 297
Data columns (total 3 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   mcc       298 non-null    int64
 1   mcc_name  298 non-null    object
 2   page      298 non-null    int64
dtypes: int64(2), object(1)
memory usage: 7.1+ KB